# Generated by Django 4.0.1 on 2022-01-05 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_tasks_ativo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tasks',
            new_name='Task',
        ),
    ]
