# Generated by Django 4.0.1 on 2022-01-05 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_tasks_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='complexity',
            field=models.CharField(choices=[('test', 'Facil'), ('test', 'Medio'), ('test', 'Dificil')], default='Facil', max_length=7, verbose_name='Complexidade'),
        ),
    ]
