# Generated by Django 4.0.1 on 2022-01-05 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_task_complexity'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='duration',
            field=models.CharField(blank=True, default='2hr ~ 4hr', editable=False, max_length=9, verbose_name='Duração'),
        ),
    ]
