# Generated by Django 4.0.1 on 2022-01-07 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_task_complexity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'Task', 'verbose_name_plural': 'Tasks'},
        ),
        migrations.AlterField(
            model_name='task',
            name='complexity',
            field=models.CharField(choices=[('Facil', 'Facil'), ('Medio', 'Medio'), ('Dificil', 'Dificil')], default='Facil', max_length=7, verbose_name='Complexidade'),
        ),
    ]
